### 程序中错误处理

在合约代码中进行错误处理，主要指的是通过各种条件的检查，针对不符合预期的情况，进行错误捕获或抛出错误。

如果在程序中抛出了错误，不论是我们程序抛出的错误，或者是出现程序未处理的情况，**EVM 都会回滚交易**。

eg:

if(msg.sender != owner) { throw; }等价于

- `if(msg.sender != owner) { revert(); }`
- `assert(msg.sender == owner);`
- `require(msg.sender == owner);`



-  **require()**
  - 通常用来在执行逻辑前检查输入或合约状态变量是否满足条件，以及验证外部调用的返回值时候满足条件，在条件不满足时抛出异常。
  - 通常，你应该最常使用 `require`
  - 通常，它将在函数的**开头**
  - 退还任何剩余的 gas，并允许你返回一个值
  - `require` 失败时则执行回退操作（操作码 0xfd）
- **assert()**
  - 检查[上溢/下溢](https://github.com/ConsenSys/smart-contract-best-practices#integer-overflow-and-underflow)，即: c = a+b;assert(c > b)
    检查[常量](https://en.wikipedia.org/wiki/Invariant_(computer_science))，即:assert(this.balance >= totalSupply)
  - 进行更改后验证状态
  - 预防永远不可能发生的情况,为了防止发生任何非常糟糕的事情
  - 通常，你可能会较少使用 assert
  - 通常，它将在函数结束时使用。
  - 消耗所有剩余的 Gas
  - `assert` 失败时执行无效操作（操作码 0xfe）

- **revert()**

  - 处理与 require() 相同类型的情况，但逻辑更复杂。
  - 如果你有一些复杂的嵌套 `if/else` 逻辑流程，你可能会发现使用 `revert()` 而不是 `require()` 是有意义的。
  - 退还任何剩余的 gas，并允许你返回一个值
  - `revert` 失败时则执行回退操作（操作码 0xfd）

- **自定义错误**

  - 在 Solidity 0.8.0 之后，Solidity 引入了**自定义错误**机制（`custom errors`），提供了一种更加 Gas 高效的错误处理方式。

  - 自定义错误比 `require` 或 `revert` 的字符串消息消耗更少的 Gas，因为自定义错误只传递函数选择器和参数。

  - 自定义错误通过 `error` 关键字声明。

  - 自定义错误不会在错误消息中传递冗长的字符串

  - ```
    pragma solidity ^0.8.0;
    contract CustomErrorExample {
        error Unauthorized(address caller);  // 自定义错误
        address public owner;
        constructor() {
            owner = msg.sender;
        }
        function restrictedFunction() public {
            if (msg.sender != owner) {
                revert Unauthorized(msg.sender);  // 使用自定义错误
            }
        }
    }
    ```

-  **try/catch** **错误捕获**
  - Solidity 0.6.0 版本后引入了 `try/catch` 结构，用于捕获外部合约调用中的异常。
  - 此功能允许开发者捕获和处理外部调用中的错误。
  - 捕获外部合约调用失败时的错误，而不让整个交易失败。
  - 在同一个交易中可以对失败的调用进行处理或重试。